# Introduction to NumPy

In [1]:
# import numpy
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\yadwi\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays 

In [4]:
# creating arrays of zeros of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# creating arrays of ones of size 10
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# creating an array of an arbitrary number e.g., 2.5 of size 10 using the function full
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
# convert a python list of [1,2,3,4,5,6,7] to array using function np.array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# to access an element of an array simply refer to its index. 
# Index starts from 0 in python, therefore to access the third element of array a use:
a[2]

3

In [11]:
# to replace an element from an array, use the assignment operator
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  6,  7])

In [12]:
# to create a range of array
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
# an important function is linspace. It creates numbers from a start and end specified number
# this command creates an array starting from 0 to 100 of size 11
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays

In [16]:
# to create a multi-dimensional array, use the same function but specify the dimension of the array
# this will create an array of five rows and two columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
# create an array from a Python list of list
# this will create a 2-D array
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [20]:
# to access a number from a 2-D array, proivde the row and column number
n[0,1]

2

In [21]:
# to change the element of the array use the assignment operator
n[0,1]=20

In [22]:
# to access the entire row, instead of passing two indices, just specify the row number
n[0]

array([ 1, 20,  3])

In [23]:
# to change the elements from the last row, just pass the desired list
n[2]=[1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
# to access a column, use the colon operator for the rows
# colon operator means to return all the rows
n[:,1]

array([20,  5,  1])

In [26]:
# to aceess the last column
n[:,2]

array([3, 6, 1])

In [28]:
# or assign the last column to something else
n[:,2]= [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays

In [29]:
# to generate a random array, use np.random.rand function with number of rows and columns
np.random.rand(5,2)

array([[0.66068113, 0.49548798],
       [0.35025557, 0.60116513],
       [0.44408992, 0.21143608],
       [0.60721556, 0.26887905],
       [0.77985323, 0.6200283 ]])

In [44]:
# the numbers generated using the np.random.rand are pseudo random,
# therefore everytime when we execute the random.rand command, we will get new set of numbers
np.random.rand(2,2)

array([[0.29965467, 0.26682728],
       [0.62113383, 0.52914209]])

In [47]:
# however to fix these number for reproducibility we can set the seed of this random generator
np.random.seed(2)
np.random.randn(2,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081]])

In [46]:
# to get numbers between 0 & 100, just multiply the array with number 100
100*np.random.rand(2,2)

array([[42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664]])

In [50]:
# to generate random integers, use function randint by specifying lowest and highest numbers
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [53]:
# let's create a range of array of size 5 
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
# now add one to each of it's element
a + 1

array([1, 2, 3, 4, 5])

In [55]:
# or multiply each element with 2

a *2 

array([0, 2, 4, 6, 8])

In [57]:
# more operations
b = (10 + (a*2)) **2

In [58]:
# element wise sum of two arrays

a + b

array([100, 145, 198, 259, 328])

In [59]:
a/b+10

array([10.        , 10.00694444, 10.01020408, 10.01171875, 10.01234568])

## Comparison operations

In [61]:
# element-wise comparisons
a >= 2

array([False, False,  True,  True,  True])

In [62]:
# to check which elements of array a are larger than elements of array b
a > b

array([False, False, False, False, False])

In [65]:
# to check which elements of a are less than elements of b
a[a<b]

array([0, 1, 2, 3, 4])

In [67]:
# to get the minimum and maximum numbers from an array
a.min()

0

In [68]:
a.max()

4

In [69]:
# compute sum of all elements of arrays
a.sum()

10

In [70]:
# to calculate std. deviation
a.std()

1.4142135623730951